name: POC sonarqube

on:
  push:
    branches: [ ci ]

jobs:
  QA-Analysis:
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      - name: Build with Maven
        run: |
          mvn clean package

      - name: Depcheck - HTML
        uses: dependency-check/Dependency-Check_Action@main
        id: DepcheckHTML
        with:
          project: 'Project-DDD'
          path: '.'
          format: 'HTML'
          args: >
            --failOnCVSS 7
            --enableRetired

      - uses: pmd/pmd-github-action@v1
        with:
          rulesets: 'ruleset.xml'

      - name: Upload Test results
        uses: actions/upload-artifact@master
        with:
          name: Dependency-Check-Report
          path: ${{github.workspace}}/target/dependency-check-report

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONARQUBE_HOST }}
